name: build
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: [ubuntu-latest, self-hosted]
    steps:
    - uses: actions/checkout@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.token }}
    - name: Build the Docker image
      run: docker build -t ghcr.io/$GITHUB_REPOSITORY .
    - name: Docker push
      run: docker push ghcr.io/$GITHUB_REPOSITORY
